#ifndef PEONPAD_SDL3_COMPAT_SDL_H
#define PEONPAD_SDL3_COMPAT_SDL_H

#ifndef SDL_ENABLE_OLD_NAMES
#define SDL_ENABLE_OLD_NAMES
#endif

#include <SDL3/SDL.h>

#ifndef SDL_FINGERCANCEL
#define SDL_FINGERCANCEL SDL_EVENT_FINGER_CANCELED
#endif

#ifndef SDL_WINDOW_FULLSCREEN_DESKTOP
#define SDL_WINDOW_FULLSCREEN_DESKTOP SDL_WINDOW_FULLSCREEN
#endif

#endif
